import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from 'next/font/google'
import { RecoilRoot } from "recoil";

const roboto = Roboto({
  weight: ['400', '700'],
  style: 'normal', 
  variable:"--font-regular",
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Colabra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
      <RecoilRoot>
        {children}
        </RecoilRoot>
      </body>
    </html>
  );
}
